name: Commit lint

on:
  pull_request:
    branches: [ "master" ]

  workflow_call:
    outputs:
      url:
        description: Workflow URL
        value: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run unit tests
        run: npm run test-ci

      - name: Archive unit test result
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: ./test-report.html

      - name: Install XVFB
        run: sudo apt-get install xvfb -y

      - name: Run XVFB
        run: |
          export DISPLAY=:1
          Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run e2e tests
        run: |
          npx playwright install
          xvfb-run npm run e2e:ci

      - name: Archive e2e test result
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-report
          path: playwright-report/index.html