name: CI

on:
  push:
    branches: [ "master", "feature1"]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm ci,
          npx playwright install,
          npm install conventional-changelog-conventionalcommits,
          npm install commitlint@latest

      - name: Validate current commit with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose