name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      pages-url:
        description: GH pages URL
        value: "https://${{github.repository_owner}}.github.io/${{github.event.repository.name}}"
      deploy-status:
        description: Deploy status
        value: ${{jobs.deploy.outputs.deploy-status}}
      workflow-url:
        description: Workflow URL
        value: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{steps.deploy.outputs.deployment-status}}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GH pages
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build