name: Release

on:
  push:
    tags:
      - v\d+

permissions:
  issues: write
  contents: write

jobs:
  test:
    uses: ./.github/workflows/ci-test.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: test
  changelog:
    uses: ./.github/workflows/changelog.yml
    if: ${{ always() }}
    needs:
      - test
      - deploy
    with:
      release: ${{ github.ref_name }}
      review-verified: ${{ needs.review.result == 'success' }}
      review-url: ${{ needs.review.outputs.url }}
      deploy-verified: ${{ contains(fromJson('["success", "skipped"]'), needs.deploy.outputs.deploy-status) }}
      deploy-url: ${{ needs.deploy.outputs.workflow-url }}
      pages-url: ${{ needs.deploy.outputs.pages-url }}