name: Make release

on:
  push:
    tags:
      - 'v[0-9]+'

permissions:
  issues: write
  contents: write

jobs:
  test:
    uses: ./.github/workflows/ci-test.yml

  deploy:
    needs:
      - test
    steps:
      - name: Deploy to GH pages
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
    outputs:
      deploy-status: ${{steps.deploy.outputs.deployment-status}}
      pages-url:
        description: GH pages URL
        value: "https://${{github.repository_owner}}.github.io/${{github.event.repository.name}}"
      workflow-url:
        description: Workflow URL
        value: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  changelog:
    needs:
      - test
      - deploy
    steps:
      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ inputs.release }}
          excludeTypes:
      - name: Move changelog
        run: cat CHANGELOG.md >> .github/ISSUE_TEMPLATE.md
      - name: Create issue
        id: issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ github.ref_name }}
          reviewVerified: ${{ needs.review.result == 'success' }}
          reviewUrl: ${{ needs.review.outputs.url }}
          deployVerified: ${{ contains(fromJson('["success", "skipped"]'), needs.deploy.outputs.deploy-status) }}
          deployUrl: ${{ needs.deploy.outputs.workflow-url }}
          pagesUrl: ${{ needs.deploy.outputs.pages-url }}
        with:
          assignees: ${{ github.actor }}
          update_existing: true
          search_existing: all
      - name: Report status
        if: ${{!(inputs.review-verified && inputs.deploy-verified)}}
        run: gh issue comment ${{steps.issue.outputs.number}} --body "Can't close because of failed processess"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Close issue
        if: ${{inputs.review-verified && inputs.deploy-verified}}
        run: gh issue close ${{steps.issue.outputs.number}} --comment "Close due to successful release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}